### ISSUE TITLE
Can't connect to local Bazel server at an amd64 Ubuntu VM running on a M1 Mac

### ISSUE THREAD

**Issue by pot8os** [bazelbuild/bazelisk#341]
Hello team, I'm getting stuck with a weird behavior on Bazel running in a VM. It's easy to reproduce so hope you could address it.

### Environment

- Host: M1 Pro macOS Monterey 12.5
- VM: amd64 Ubuntu 20.04 controlled by [lima](https://github.com/lima-vm/lima)
    <details>
    <summary>Provisioning script to make Ubuntu image</summary>
    
    ```yaml
    arch: "x86_64"
    images:
        - location: "https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
        arch: "x86_64"
    
    mounts:
        - location: "/tmp/lima"
        writable: true
    
    containerd:
        system: false
        user: false
    ```
     
    </details>

   - Bazelisk version: v1.12.0 (bazelisk-linux-amd64)

### How to reproduce

1. Dive into the VM image using `limactl shell`
2. Install `bazelisk` binary
3. Checkout [examples](https://github.com/bazelbuild/examples) repository
4. $ cd examples/cpp-tutorial/stage1
5. $ bazelisk build //main:hello-world

### Expected

Bazel works well.

### Actual

Aborted since it couldn't connect to local Bazel server for some reason. It's 100% reproducible so far.

```sh
***@lima-ubuntu:~/examples/cpp-tutorial/stage1$ bazelisk build //main:hello-world
Starting local Bazel server and connecting to it...
... still trying to connect to local Bazel server after 10 seconds ...
... still trying to connect to local Bazel server after 20 seconds ...
... still trying to connect to local Bazel server after 30 seconds ...
... still trying to connect to local Bazel server after 40 seconds ...
... still trying to connect to local Bazel server after 50 seconds ...
... still trying to connect to local Bazel server after 60 seconds ...
... still trying to connect to local Bazel server after 70 seconds ...
... still trying to connect to local Bazel server after 80 seconds ...
... still trying to connect to local Bazel server after 90 seconds ...
... still trying to connect to local Bazel server after 100 seconds ...
... still trying to connect to local Bazel server after 110 seconds ...
FATAL: couldn't connect to server (3308) after 120 seconds.
```

Thanks!
